Repository abduljalilpalala/sats-project, pull requests merged in 2022-10, with the labels that each got.

#1 [SATS-083] - [Markup] Create User Registration Page
  client/.prettierrc
  client/package.json
  client/pages/index.tsx
  client/public/images/404.png
  client/public/images/logo.png
  client/public/images/under-construction.png
  client/src/components/molecules/AuthForm/index.tsx
  client/src/components/organisms/AuthHeader/index.tsx
  client/src/components/templates/AuthLayout/index.tsx
  client/src/helpers/classNames.tsx
  client/src/pages/404.tsx
  client/src/pages/_app.tsx
  client/src/pages/_document.tsx
  client/src/pages/api/hello.ts
  client/src/pages/index.tsx
  client/src/pages/login.tsx
  client/src/pages/register.tsx
  client/src/shared/css/globals.css
  client/src/shared/css/tailwind.css
  client/src/shared/icons/SpinnerIcon.tsx
  client/src/shared/types/index.ts
  client/src/shared/validation/index.ts
  client/src/utils/UnderConstruction.tsx
  client/styles/globals.css
  client/tailwind.config.js
  client/tsconfig.json
  client/yarn.lock
Labels: for review

#4 [SATS-089] - [Markup] Create Admin Login and Under Construction Dashboard Page
  client/public/images/bg-slsu.png
  client/public/images/bg-slsu2.png
  client/public/images/bg-slsu3.jpg
  client/src/components/templates/AdminLayout/index.tsx
  client/src/pages/admin/dashboard.tsx
  client/src/pages/admin/index.tsx
Labels: for review

#3 [SATS-085] - [FE] Integrate User Registration Functionality
  api/app/Http/Controllers/Auth/RegisterUserController.php
  api/app/Http/Requests/RegisterUserRequest.php
  api/app/Models/User.php
  client/package.json
  client/src/components/molecules/AuthForm/index.tsx
  client/src/hooks/auth.ts
  client/src/hooks/axiosError.ts
  client/src/pages/_app.tsx
  client/src/pages/register.tsx
  client/src/shared/lib/axios.ts
  client/src/shared/types/index.ts
  client/src/utils/UnderConstruction.tsx
  client/src/utils/handleAxiosError.ts
  client/yarn.lock
Labels: Approved by Joshua Galit

#7 [SATS-088] - [FE] Integrate User Login Functionality
  client/src/components/molecules/AuthForm/index.tsx
  client/src/hooks/auth.ts
  client/src/pages/login.tsx
  client/src/pages/register.tsx
Labels: for review, Approved by Joshua Galit

#8 [SATS-090] - [BE] Implement Admin Login Functionality
  api/database/seeders/AdminSeeder.php
  api/database/seeders/DatabaseSeeder.php
Labels: for review, Approved by Joshua Galit

#9 [SATS-091] - [FE] Integrate Admin Login Functionality
  client/src/components/molecules/AuthForm/index.tsx
  client/src/hooks/auth.ts
  client/src/pages/admin/index.tsx
  client/src/pages/register.tsx
  client/src/shared/data/roleConstant.ts
  client/src/shared/types/index.ts
Labels: for review, Approved by Joshua Galit

#10 [SATS-083-1] - [Markup] Create User Registration Page
  client/public/images/bg-alumni-login.png
  client/public/images/bg-alumni-register.png
  client/src/components/molecules/AuthForm/index.tsx
  client/src/components/templates/AuthLayout/index.tsx
  client/src/pages/_document.tsx
  client/src/pages/login.tsx
  client/src/pages/register.tsx
  client/src/shared/css/tailwind.css
  client/src/shared/types/index.ts
  client/src/shared/validation/index.ts
Labels: for review

#11 [SATS-404] - [Markup] Create 404 Error Page
  client/public/images/not-found.png
  client/src/pages/404.tsx
Labels: for review

#12 [SATS-089-1] - [Markup] Create Admin Login Page
  client/src/components/molecules/AuthForm/index.tsx
  client/src/pages/admin/index.tsx
  client/src/pages/login.tsx
  client/src/pages/register.tsx
Labels: for review

#13 [SATS-300] - [Markup] Create User Newsfeed
  client/next.config.js
  client/public/images/animated-avatar.jpg
  client/src/components/organisms/AlumniHeader/index.tsx
  client/src/components/templates/AdminLayout/index.tsx
  client/src/components/templates/AlumniLayout/index.tsx
  client/src/pages/_document.tsx
  client/src/pages/index.tsx
  client/src/shared/data/alumniData.ts
  client/src/shared/interfaces/index.ts
  client/tailwind.config.js
Labels: for review

#14 [SATS-104-1] - [Markup] Create Admin Layout
  client/package.json
  client/src/components/organisms/AdminHeader/index.tsx
  client/src/components/organisms/AdminSidebar/index.tsx
  client/src/components/organisms/Sidebar/index.tsx
  client/src/components/templates/AdminLayout/index.tsx
  client/src/components/templates/AlumniLayout/index.tsx
  client/src/pages/_document.tsx
  client/src/shared/data/sidebarLinks.ts
  client/src/shared/interfaces/index.ts
  client/tailwind.config.js
  client/yarn.lock
Labels: for review

#15 [SATS-107] - [Markup] Create Admin Dashboard
  client/package.json
  client/src/components/templates/Card/index.tsx
  client/src/hooks/useWindowDimensions.ts
  client/src/pages/admin/dashboard.tsx
  client/tailwind.config.js
  client/yarn.lock
Labels: dependent, for review, Approved by Joshua Galit

#17 [SATS-545] - [Markup] Create Admin Manage Posts Page
  client/package.json
  client/src/components/molecules/AdminPost/index.tsx
  client/src/components/templates/AdminLayout/index.tsx
  client/src/hooks/useHydrationBypass.tsx
  client/src/pages/_app.tsx
  client/src/pages/admin/manage-post.tsx
  client/src/shared/icons/MoreIcon.tsx
  client/src/utils/getDaysAgo.tsx
  client/tailwind.config.js
  client/yarn.lock
Labels: dependent, for review, Approved by Joshua Galit

#18 [SATS-111] - [Markup] Create Admin Manage Users Page
  client/public/images/avatar.png
  client/src/pages/admin/manage-user.tsx
  client/src/utils/getApplicationStatus.tsx
Labels: dependent, for review

#19 [SATS-304] - [Markup] Create Admin Settings
  client/src/components/atoms/SubmitButton/index.tsx
  client/src/components/atoms/SwitchToggle/index.tsx
  client/src/components/molecules/AdminSettings/index.tsx
  client/src/components/organisms/AdminSidebar/index.tsx
  client/src/components/templates/ModalCard/index.tsx
  client/src/hooks/useWindowDimensions.ts
  client/src/pages/admin/dashboard.tsx
  client/src/pages/admin/manage-user.tsx
  client/src/shared/icons/CloseIcon.tsx
  client/src/shared/icons/TaskIcon.tsx
  client/src/utils/truncate.ts
Labels: dependent, for review, Approved by Joshua Galit
