Repository abduljalilpalala/sats-project, pull requests merged in 2022-11, with the labels that each got.

#21 [SATS-909] - [FE] Re-implement Login and Register Functionality
  api/app/Enums/EmploymentStatusEnum.php
  api/app/Http/Controllers/Auth/AuthController.php
  api/app/Http/Controllers/Auth/RegisterUserController.php
  api/app/Http/Requests/RegisterUserRequest.php
  api/app/Models/Batch.php
  api/app/Models/EmploymentStatus.php
  api/app/Models/User.php
  api/composer.json
  api/composer.lock
  api/config/media-library.php
  api/database/migrations/2022_10_30_181525_rename_employee_statuses_table.php
  api/database/migrations/2022_10_30_182326_rename_employee_status_id_in_users_table.php
  api/database/migrations/2022_10_30_190744_create_media_table.php
  api/database/migrations/2022_10_30_190856_create_batches_table.php
  api/database/migrations/2022_10_30_191040_add_batch_id_to_users_table.php
  api/database/seeders/AdminSeeder.php
  api/database/seeders/BatchSeeder.php
  api/database/seeders/DatabaseSeeder.php
  api/database/seeders/EmployeeStatusSeeder.php
  api/public/assets/avatars/default.png
  api/routes/auth.php
  client/src/components/molecules/AdminSettings/index.tsx
  client/src/components/molecules/AuthForm/index.tsx
  client/src/hooks/auth.ts
  client/src/hooks/axiosError.ts
  client/src/pages/admin/index.tsx
  client/src/pages/login.tsx
  client/src/pages/register.tsx
  client/src/shared/types/index.ts
  client/src/shared/validation/index.ts
Labels: For Code Review 💻, Approved by Joshua ✅, Approved by John ✅

#23 [SATS-516] - [BE] Implement Approve User Functionality
  api/app/Http/Controllers/UserController.php
  api/routes/api.php
Labels: dependent, Approved by John ✅

#24 [SATS-519] - [BE] Implement Reject Application Functionality
  api/app/Http/Controllers/UserController.php
  api/routes/api.php
Labels: dependent, Approved by John ✅

#25 [SATS-521] - [BE] Implement Fetch, Creating, Updating and Deleting Posts Functionality
  api/app/Http/Controllers/PostController.php
  api/app/Http/Controllers/UserController.php
  api/app/Http/Requests/PostRequest.php
  api/app/Http/Resources/PostResource.php
  api/app/Models/Post.php
  api/database/migrations/2022_10_31_161155_create_posts_table.php
  api/routes/api.php
Labels: dependent, Approved by John ✅

#26 [SATS-523] - [BE] Implement Update Admin Password Functionality
  api/app/Http/Controllers/UpdatePasswordController.php
  api/app/Http/Requests/UpdatePasswordRequest.php
  api/app/Rules/MatchOldPassword.php
  api/routes/api.php
Labels: dependent, Approved by John ✅

#27 [SATS-525] - [BE] Implement Set On/Off SMS Messaging Functionality
  api/app/Http/Controllers/AdminSettingController.php
  api/app/Models/AdminSetting.php
  api/database/migrations/2022_10_31_195721_create_admin_settings_table.php
  api/database/seeders/AdminSettingSeeder.php
  api/database/seeders/DatabaseSeeder.php
  api/routes/api.php
Labels: dependent, Approved by John ✅

#29 [SATS-524] - [FE] Integrate Update Admin Password Functionality
  api/.env.example
  api/composer.lock
  api/config/cors.php
  client/.env.example
  client/src/components/molecules/AdminSettings/index.tsx
  client/src/hooks/admin/adminHooks.ts
  client/src/hooks/auth.ts
  client/src/pages/admin/index.tsx
  client/src/shared/lib/axios.ts
  client/src/utils/setData.ts
Labels: For Code Review 💻, Approved by Joshua ✅

#30 [SATS-526] - [FE] Integrate Set On/Off SMS Messaging Functionality
  api/app/Http/Controllers/AdminSettingController.php
  api/routes/api.php
  client/src/components/atoms/SwitchToggle/index.tsx
  client/src/components/molecules/AdminSettings/index.tsx
  client/src/hooks/admin/adminHooks.ts
Labels: For Code Review 💻

#32 [SATS-520] - [FE] Integrate Reject Application Functionality
  api/app/Http/Controllers/UserController.php
  client/src/hooks/admin/adminHooks.ts
  client/src/hooks/useFetch.ts
  client/src/pages/admin/manage-user.tsx
Labels: For Code Review 💻

#36 [SATS-544] - [FE] Integrate Update Password Functionality
  api/app/Http/Controllers/Auth/AuthController.php
  client/src/components/molecules/AlumniSettings/index.tsx
  client/src/components/molecules/AlumniSettings/types.ts
  client/src/components/organisms/AlumniHeader/index.tsx
  client/src/components/templates/AlumniLayout/index.tsx
  client/src/hooks/auth.ts
  client/src/hooks/user/userHooks.ts
  client/src/shared/interfaces/index.ts
  client/src/shared/types/index.ts
Labels: For Code Review 💻

#40 [SATS-542] - [BE] Implement Update and Remove Avatar Functionality
  api/.env.example
  api/app/Http/Controllers/UserAvatarController.php
  api/app/Http/Requests/UserAvatarRequest.php
  api/app/Models/User.php
  api/routes/api.php
Labels: For Code Review 💻, Approved by Joshua ✅

#41 [SATS-540] - [BE] Implement Update Name, Email and Phone Number Functionality
  api/app/Http/Controllers/UpdateUserController.php
  api/app/Http/Controllers/UserController.php
  api/app/Http/Requests/UpdateUserRequest.php
  api/app/Models/User.php
  api/routes/api.php
Labels: For Code Review 💻, Approved by Joshua ✅

#42 [SATS-991] - [BE] Implement Update ID Number, Birth Date and Employment Status Functionality
  api/app/Http/Requests/RegisterUserRequest.php
  api/app/Http/Requests/UpdateUserRequest.php
  api/app/Http/Resources/AvatarResource.php
Labels: For Code Review 💻, Approved by Joshua ✅

#39 [SATS-891] - [Bugfix] Fix sidebar bug
  client/src/components/organisms/AdminDrawer/index.tsx
  client/src/components/organisms/AdminHeader/index.tsx
  client/src/components/organisms/AdminSidebar/index.tsx
  client/src/components/templates/AdminLayout/index.tsx
  client/src/hooks/auth.ts
Labels: For Code Review 💻

#43 [SATS-993] - [FE] Integrate Update ID Number, Birth Date and Employment Status Functionality
  client/src/components/molecules/AlumniSettings/index.tsx
  client/src/components/molecules/AlumniSettings/types.ts
  client/src/components/templates/AlumniLayout/index.tsx
  client/src/shared/validation/index.ts
Labels: For Code Review 💻

#44 [SATS-541] - [FE] Integrate Update Name, Email and Phone Number Functionality
  client/src/components/molecules/AlumniSettings/index.tsx
  client/src/components/molecules/AlumniSettings/types.ts
  client/src/shared/validation/index.ts
Labels: don't merge, dependent, For Code Review 💻

#45 [SATS-543] - [FE] Integrate Update and Remove Avatar Functionality
  client/next.config.js
  client/src/components/molecules/AlumniSettings/index.tsx
  client/src/components/organisms/AlumniHeader/index.tsx
  client/src/components/templates/AlumniLayout/index.tsx
  client/src/shared/interfaces/index.ts
Labels: don't merge, dependent, For Code Review 💻

#38 [SATS-530] - [FE] Fetch and Display Alumni's and Posts in User Newsfeed Page
  api/app/Http/Controllers/AlumniController.php
  api/app/Http/Controllers/PostController.php
  api/routes/api.php
  client/next.config.js
  client/src/components/atoms/Skeletons/NewsFeedPostSkeleton.tsx
  client/src/components/atoms/Skeletons/ProfileCardSkeleton.tsx
  client/src/components/templates/AdminLayout/index.tsx
  client/src/components/templates/AlumniLayout/index.tsx
  client/src/hooks/admin/adminHooks.ts
  client/src/hooks/user/alumniHooks.ts
  client/src/hooks/user/newsFeedHooks.ts
  client/src/pages/admin/manage-user.tsx
  client/src/pages/index.tsx
  client/src/shared/interfaces/index.ts
  client/src/utils/handleImageError.ts
Labels: For Code Review 💻
